airflow_db:
  target: dev
  outputs:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT') | as_number }}"
      dbname: postgres
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      threads: 4
  dev:
